name: windows-x64-gpu-vs2019
on: [push, pull_request]
jobs:
  windows-vs2019-gpu:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "VulkanSDK"
        key: VulkanSDK-1.1.114.0-Installer
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true -OutFile VulkanSDK-1.1.114.0-Installer.exe
        7z x -aoa ./VulkanSDK-1.1.114.0-Installer.exe -oVulkanSDK
        Remove-Item .\VulkanSDK\Demos, .\VulkanSDK\glslang, .\VulkanSDK\Samples, .\VulkanSDK\shaderc, .\VulkanSDK\spirv-tools, .\VulkanSDK\Third-Party, .\VulkanSDK\Tools, .\VulkanSDK\Tools32 -Recurse
    - name: configure
      run: |
        $env:VULKAN_SDK="$(pwd)/VulkanSDK"
        mkdir build; cd build
        cmake ../src
    - name: build
      run: cmake --build build --config Release -j 2
    - name: deploy
      run: |
        mkdir srmd-ncnn-vulkan-artifact
        Copy-Item -Path "build\Release\srmd-ncnn-vulkan.exe" -Destination "srmd-ncnn-vulkan-artifact"
        Copy-Item -Path "models\*" -Destination "srmd-ncnn-vulkan-artifact"
    - uses: actions/upload-artifact@v2
      with:
        name: srmd-ncnn-vulkan-artifact
        path: srmd-ncnn-vulkan-artifact
